cd: add validation steps before deploying the app

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -101,13 +101,31 @@ jobs:
         run: |
           docker run --rm -v "${{ github.workspace }}/deployment/nginx/conf.d/app.conf:/etc/nginx/conf/nginx.conf" yandex/gixy /etc/nginx/conf/nginx.conf
 
+  check-port:
+    runs-on: ubuntu-latest
+    name: Check if Port 22 is Open
+    outputs:
+      port_open: ${{ steps.check.outputs.port_open }}
+    steps:
+      - name: Check Port 22
+        id: check
+        run: |
+          if nc -z -w5 "${{ secrets.VPS_IP }}" 22; then
+            echo "Port 22 is open."
+            echo "port_open=true" >> $GITHUB_OUTPUT
+          else
+            echo "::warning::Port 22 is not open on ${{ secrets.VPS_IP }}. Please open port 22 before proceeding."
+            echo "port_open=false" >> $GITHUB_OUTPUT
+          fi
+
   deploy:
     runs-on: ubuntu-latest
     name: Deploy
     needs: 
       - build-frontend-docker-image
       - build-backend-docker-image
-    if: ${{ github.event.workflow_run.head_branch == 'main' }}
+      - check-port
+    if: ${{ github.event.workflow_run.head_branch == 'main' && needs.check-port.outputs.port_open == 'true' }}
     environment:
       name: prod 
     steps:
@@ -137,6 +155,15 @@ jobs:
           port: 22
           script: |
             cd deployments/${{ github.repository }}/deployment/
+
+            REQUIRED_NGINX_FILES="certs/cf-origin.crt certs/cf-origin.key conf.d/app.conf"
+            for file in $REQUIRED_NGINX_FILES; do
+              if [ ! -f "$file" ]; then
+                echo "Error: Required NGINX file '$file' not found. Ensure those are present before starting the app."
+                exit 1
+              fi
+            done
+
             export GH_API_TOKEN=${{ secrets.GH_API_TOKEN }}
             docker compose -f docker-compose.subst.yml pull
             # docker compose -f docker-compose.subst.yml up -d
